// "use client"



import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/Navbar'
import Footer from '@/app/components/Footer'
import { Suspense } from 'react'
import Loading from './loading'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'IISERB ECOMMERCE',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      <Suspense fallback={<Loading />}>
          {children}
          </Suspense>
        <Footer />
      </body>
    </html>
  )
}
